name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # This runs daily at midnight UTC (you can change this to your preferred schedule)
      

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Git configuration
      run: |
        git config user.name 'Ashish kumar Singh'
        git config user.email 'as2429539@gmail.com'
        
    - name: Make changes
      run: |
        # Your script to make changes
        git add .
        git commit -m "Automated commit"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin main
